services:
  # Backend Java Spring Boot
  app:
    build:
      context: ./Tgos
      dockerfile: Dockerfile
    container_name: tgos_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8090}:8089"
    environment:
      # Configurações de Cache (Redis) e Mensageria (RabbitMQ)
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-guest}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-guest}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  # Cache em Memória
  redis:
    image: redis:alpine
    container_name: tgos_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"

  # Gerenciador de Mensagens e Filas
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: tgos_rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_AMQP_PORT:-5673}:5672"         # Protocolo AMQP externo
      - "${RABBITMQ_MANAGEMENT_PORT:-15673}:15672" # Painel Web do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
